Dac6 409
hmrc/enter-cross-border-arrangements-frontend pull request #46
Opened 2020-12-14 16:21 UTC by ers2015112

2020-12-15 14:09 UTC, helensoniega commented on app/controllers/taxpayer/WhatIsTaxpayersStartDateForImplementingArrangementController.scala
> +       case None => "the individual"
You can also call the getIndividualName and getOrganisationName in JourneyHelpers

2020-12-15 14:13 UTC, helensoniega commented on app/utils/rows/TaxpayerRows.scala
> +      Row(
Can be refactored to use toRow()

2020-12-15 14:17 UTC, helensoniega commented on conf/views/taxpayer/selectType.njk
> +            errorMessage: form.confirm.error
Shouldn't this be form.selectType.error?

2020-12-15 14:17 UTC, cameronstalker1 requested changes

2020-12-15 14:19 UTC, helensoniega commented on test/controllers/taxpayer/CheckYourAnswersTaxpayersControllerSpec.scala
> +    println(s"\n\n\n$summaryRows\n\n\n")
Remove println

2020-12-16 09:59 UTC, helensoniega approved these changes

2020-12-17 13:50 UTC, merged